### ISSUE TITLE
[idea] easy screen video to gif script

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/mozilla_science_fellowship#6]
would be nice to have a nice workflow/script for creating gifs - e.g. for instructions or for other fun things

**Comment by blahah** [comment]
there are some of these :)

I use gifgrabber, and there are some nice ones for recording terminal work that I've used before

**Comment by joeyklee** [comment]
nice! I figured there must be some nice ones out there! thanks :)

**Comment by blahah** [comment]
Realised I didn't help much with the terminal side:

https://asciinema.org/
